version: '3.6'

services:
  api:
    build: .
    image: application
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["./wait-for-it.sh","db:5432", "--","./app"]
  db:
    image: 'bitnami/postgresql:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=application
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=1qazxsw2