basePath: /v1
definitions:
  web.vesionOut:
    properties:
      code:
        type: string
      message:
        type: string
      releaseTime:
        type: string
      releaseVersion:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a Rest Template App.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Rest Template App
  version: 0.0.1
paths:
  /system/version:
    get:
      consumes:
      - application/json
      description: View Version app
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.vesionOut'
      summary: Get API version and release information
      tags:
      - go-rest-template-app
schemes:
- http
- https
swagger: "2.0"
